events {}

http {
    upstream backend {
        server linux1:8080;
        #server linux2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}